
## Cluster Secrets by Environments

cluster_sp_id_key: clientId
cluster_sp_secret_key: clientSecret
cluster_tenant_id_key: tenantId
cluster_subscription_id_key: subId
pull_secret_akv_key: pullSecret


## ARO Cluster Build Secrets


tags:
  createdBy: "test-user"

## Parameters if needed to create Network Resources Values
vnet:
  name: "ansible-aro-cluster-vnet"
  location: eastus
  network_rg: aro-cluster-network-rg 
  address_cidr: 10.0.0.0/22
  control_plane: 
    name: ansible-aro-cluster-control-subnet
    address_cidr: 10.0.0.0/23
  worker_plane:
    name: ansible-aro-cluster-worker-subnet
    address_cidr: 10.0.2.0/23

# outbound-type: Loadbalancer|UserDefinedRouting

cluster:
  conditionals:
    create_network_vnet_and_subnets: True
    specify_custom_domain: False
    specify_version: True
    specify_disk_encryption_set: False
    specify_tags: True
    encrypt_master_hosts: False
    encrypt_worker_hosts: False
    enable_preconfigured_nsg: False
    enable_fips: False
  name: ansible-aro-cluster
  cluster_resource_group:  ansible-aro-main 
  location: eastus
  domain: mycluster.com
  version: "4.14.16"
  control_instance: Standard_D8s_v3
  worker_disk: 128
  worker_node_count: 3
  worker_instance: Standard_D4s_v3 
  disk_encryption_set: ""
  network:
    vnet_name: ansible-aro-cluster-vnet
    control_subnet_name: ansible-aro-cluster-control-subnet
    worker_subnet_name: ansible-aro-cluster-worker-subnet
    vnet_rg: aro-cluster-network-rg
    outbound_type: Loadbalancer  
    ingress_visibility: Public
    api_visibility: Public
    pod_cidr: 10.128.0.0/14
    service_cidr: 172.30.0.0/16  

gitops:
  install: true
  version: "gitops-1.11"





# mas_variables:
#   IBM_ENTITLEMENT_KEY: "xxx" ## Read from AKV
#   SLS_LICENSE_ID: "xxx"  ## Read from AKV
#   SLS_LICENSE_FILE: "/path/to/entitlement.lic"  ## Read from AKV

#   MAS_INSTANCE_ID: "inst1"
#   MAS_CONFIG_DIR: "~/masconfig"
#   UDS_CONTACT_EMAIL: "xxx@xxx.com"
#   UDS_CONTACT_FIRSTNAME: "xxx"
#   UDS_CONTACT_LASTNAME: "xxx"


# test.apps.masq.$domain.com
# uat.apps.masq.$domain.com
# prod.apps.masq.$domain.com

# uds_contact:
#   email: email@redhat.com
#   first_name: Francis
#   last_name: Anyaegbu
# mas_instance_id: "inst1"
# mas_config_dir: "/home/inst1/masconfig"
# mas_entitlement_key: "xxxxxxxxxxxxxxxx"  ## Preferably read from AKV
# mas_annotations: "mas.ibm.com/operationalMode=nonproduction"


## Using ibm.mas_devops.oneclick_core
# Upload all other files in the current directory
# https://ibm-mas.github.io/ansible-devops/playbooks/oneclick-core/
IBM_ENTITLEMENT_KEY: xxx
MAS_INSTANCE_ID: inst1
MAS_CONFIG_DIR: ~/masconfig

SLS_LICENSE_ID: xxx
SLS_LICENSE_FILE: /path/to/entitlement.lic

DRO_CONTACT_EMAIL: email@redhat.com
DRO_CONTACT_FIRSTNAME: Francis
DRO_CONTACT_LASTNAME: Anyaegbu


