---
- name: Delete Cluster Resource Group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ cluster.cluster_resource_group }}"
    location: "{{cluster.location }}"
    state: absent
    force_delete_nonempty: true

