---
- block:
    - name: Create Resource Groups for VNET and Subnets
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ vnet.network_rg }}"
        location: "{{vnet.location }}"
        state: present
        tags: "{{ tags }}"
    
    - name: Create a VNET for ARO
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ vnet.network_rg }}"
        name: "{{ vnet.name }}"
        address_prefixes_cidr: "{{ vnet.address_cidr }}"
        tags: "{{ tags }}"
    
    - name: Create a Control Plane Subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ vnet.network_rg }}"
        virtual_network_name: "{{ vnet.name }}"
        name: "{{ vnet.control_plane.name }}"
        address_prefix_cidr: "{{ vnet.control_plane.address_cidr }}"
        service_endpoints:
          - service: "Microsoft.ContainerRegistry"
        private_link_service_network_policies: Disabled
      register: controlSubnet
    
    - name: Create a Worker Nodes Subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ vnet.network_rg }}"
        virtual_network_name: "{{ vnet.name }}"
        name: "{{ vnet.worker_plane.name }}"
        address_prefix_cidr: "{{ vnet.worker_plane.address_cidr }}"
        service_endpoints:
          - service: "Microsoft.ContainerRegistry"
      register: workerSubnet

    - name: Conditionally define VNET name
      set_fact:
        vnetName: "{{ vnet.name if cluster.conditionals.create_network_vnet_and_subnets else cluster.network.vnet_name }}"

    - name: Conditionally define VNET Resource Group name
      set_fact:
        vnetRG: "{{ vnet.network_rg if cluster.conditionals.create_network_vnet_and_subnets else cluster.network.vnet_rg }}"

    - name: Conditionally define Control Plane Subnet
      set_fact:
        controlSubnet: "{{ vnet.control_plane.name if cluster.conditionals.create_network_vnet_and_subnets else cluster.network.control_subnet_name }}"

    - name: Conditionally define Worker Node Subnet
      set_fact:
        workerSubnet: "{{ vnet.worker_plane.name if cluster.conditionals.create_network_vnet_and_subnets else cluster.network.worker_subnet_name }}"

  when: cluster.conditionals.create_network_vnet_and_subnets and _aro_check.clusters == {}



