---
- name: Check if cluster with same name already exists.
  azure.azcollection.azure_rm_openshiftmanagedcluster_info:
    resource_group: "{{ cluster.cluster_resource_group }}"
    name: "{{ cluster.name }}"
  register: _aro_check

- name: Get Key Vault by name
  azure_rm_keyvault_info:
    resource_group: "{{ akv_resource_group }}"
    name: "{{ vault_name }}"
    client_id: "{{ akv_read_client_id }}"
    secret: "{{ akv_read_client_secret }}"
    tenant:  "{{ tenant_id }}"
    subscription_id: "{{ subscription_id }}"
  register: keyvault
  
- name: Set key vault URI fact
  set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

- name: Read Cluster Subscription_id from AKV
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "{{ keyvaulturi }}"
    name: "{{ cluster_subscription_id_key }}"
    client_id: "{{ akv_read_client_id }}"
    secret: "{{ akv_read_client_secret }}"
    tenant:  "{{ tenant_id }}"
    subscription_id: "{{ subscription_id }}"
  register: cluster_subscription_id

- name: Extract Cluster Subscription ID into reusable Variable
  set_fact: subscriptionId="{{ cluster_subscription_id['secrets'][0]['secret'] | regex_findall('subscriptions\/([a-zA-Z0-9\-]+)') | first }}"


- block:
  
    - name: Read Cluster Service Principal from AKV - Client ID
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri: "{{ keyvaulturi }}"
        name: "{{ cluster_sp_id_key }}"
        client_id: "{{ akv_read_client_id }}"
        secret: "{{ akv_read_client_secret }}"
        tenant:  "{{ tenant_id }}"
        subscription_id: "{{ subscription_id }}"
      register: cluster_client_id
  
    - name: Read Cluster Service Principal from AKV - Client Secret
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri: "{{ keyvaulturi }}"
        name: "{{ cluster_sp_secret_key }}"
        client_id: "{{ akv_read_client_id }}"
        secret: "{{ akv_read_client_secret }}"
        tenant:  "{{ tenant_id }}"
        subscription_id: "{{ subscription_id }}"
      register: cluster_client_secret
  
    - name: Read Cluster Tenant ID from AKV
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri: "{{ keyvaulturi }}"
        name: "{{ cluster_tenant_id_key }}"
        client_id: "{{ akv_read_client_id }}"
        secret: "{{ akv_read_client_secret }}"
        tenant:  "{{ tenant_id }}"
        subscription_id: "{{ subscription_id }}"
      register: cluster_tenant_id
  
    - name: Read Pull Secret from AKV
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri: "{{ keyvaulturi }}"
        name: "{{ pull_secret_akv_key }}"
        client_id: "{{ akv_read_client_id }}"
        secret: "{{ akv_read_client_secret }}"
        tenant:  "{{ tenant_id }}"
        subscription_id: "{{ subscription_id }}"
      register: pull_secret
  
    - name: Extract Cluster Client ID into reusable Variable
      set_fact: clientId="{{ cluster_client_id['secrets'][0]['secret'] }}"

    - name: Extract Cluster Client Secret into reusable Variable
      set_fact: clientSecret="{{ cluster_client_secret['secrets'][0]['secret'] }}"
    
    - name: Extract Cluster Tenant ID into reusable Variable
      set_fact: tenantId="{{ cluster_tenant_id['secrets'][0]['secret'] }}"
    
    - name: Extract Pull Secret into Variable
      set_fact: pullSecret="{{ pull_secret['secrets'][0]['secret'] }}"

  when: _aro_check.clusters == {}