---
- debug:
    msg: "Waiting for cluster to finish provisioning."
  listen: watch-aro-installation


- name: Check cluster...
  azure.azcollection.azure_rm_openshiftmanagedcluster_info:
    resource_group: "{{ cluster.cluster_resource_group }}"
    name: "{{ cluster.name }}"
  register: _aro_check
  until: (_aro_check.clusters.properties.provisioningState == "Succeeded")
  failed_when: _aro_check.clusters.properties.provisioningState == "Failed"
  retries: 120
  delay: 60
  listen: watch-aro-installation

- fail:
    msg: "Cluster {{ azr_aro_cluster }} failed to provision."
  when: _aro_check.clusters.properties.provisioningState == "Failed"
  listen: watch-aro-installation

- set_fact:
    _cluster_ready: True
  listen: watch-aro-installation


