---
- name: Create OpenShift Clusters and Environment
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - variables/common_var.yaml
    - variables/test_var.yaml

  roles:
    - create-aro-cluster
    # - ibm.mas_devops.oneclick_core
    # - ibm.mas_devops.ibm_catalogs
    # - ibm.mas_devops.common_services
    # - ibm.mas_devops.cert_manager
    # - ibm.mas_devops.uds
    # - ibm.mas_devops.suite_install
    # - ibm.mas_devops.suite_config
    # - ibm.mas_devops.suite_verify
    # - roles/01-create-roles/test
