---
- name: Delete Cluster Resource Group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ cluster.cluster_resource_group }}"
    location: "{{ cluster.location }}"
    state: absent
    force_delete_nonempty: true

- name: Check Resource Group Delete status
  azure.azcollection.azure_rm_resourcegroup_info:
    name: "{{ cluster.cluster_resource_group }}"
    # subscription_id: "{{ subscriptionId }}"
  register: delete_cluster
  until: not delete_cluster.resourcegroups | length > 0
  retries: 120
  delay: 60

- name: Delete Network resources if cluster.conditionals.create_network_vnet_and_subnets is set to True
  when: cluster.conditionals.create_network_vnet_and_subnets
  block:
    - name: Delete a Control Plane Subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ vnet.network_rg }}"
        virtual_network_name: "{{ vnet.name }}"
        name: "{{ vnet.control_plane.name }}"
        state: absent

    - name: Delete a Worker Nodes Subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ vnet.network_rg }}"
        virtual_network_name: "{{ vnet.name }}"
        name: "{{ vnet.worker_plane.name }}"
        state: absent

    - name: Check VNET Status
      azure.azcollection.azure_rm_virtualnetwork_info:
        name: "{{ vnet.name }}"
        resource_group: "{{ vnet.network_rg }}"
      register: az_net_vnet_check

    - name: Delete VNET that hosts Control abd Worker subnets
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ vnet.network_rg }}"
        name: "{{ vnet.name }}"
        state: absent
      when: az_net_vnet_check.virtualnetworks | length > 0

    - name: Check VNET delete status
      azure.azcollection.azure_rm_virtualnetwork_info:
        name: "{{ vnet.name }}"
        resource_group: "{{ vnet.network_rg }}"
      register: az_net_vnet
      until: az_net_vnet.virtualnetworks | length < 1
      retries: 120
      delay: 5

    - name: Check VNET Resource Group delete status
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "{{ vnet.name }}"
      register: az_net_rg_check

    - name: Delete Resource Groups for VNET and Subnets
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ vnet.network_rg }}"
        location: "{{ vnet.location }}"
        force_delete_nonempty: true
        state: absent
      when: az_net_rg_check.resourcegroups | length > 0

    - name: Check VNET Resource Group delete status
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "{{ vnet.name }}"
      register: az_net_rg
      until: az_net_rg.resourcegroups | length < 1
      retries: 120
      delay: 5

- name: Cleanup Completion Message
  ansible.builtin.debug:
    msg: "Cleanup of cluster {{ cluster.name }} completed!"
