---
- name: Delete a Control Plane Subnet
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ vnet.network_rg }}"
    virtual_network_name: "{{ vnet.name }}"
    name: "{{ vnet.control_plane.name }}"
    state: absent
    
- name: Delete a Worker Nodes Subnet
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ vnet.network_rg }}"
    virtual_network_name: "{{ vnet.name }}"
    name: "{{ vnet.worker_plane.name }}"
    state: absent
    
- name: Check if the Network VNET exists
  azure.azcollection.azure_rm_virtualnetwork_info:
    name: "{{ vnet.name }}"
    resource_group: "{{ vnet.network_rg }}"
  register: az_net_vnet


- name: Delete a VNET for ARO
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ vnet.network_rg }}"
    name: "{{ vnet.name }}"
    state: absent
  ignore_errors: true
  when: az_net_vnet.virtualnetworks | length == 1

- name: Delete Resource Groups for VNET and Subnets
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ vnet.network_rg }}"
    location: "{{ vnet.location }}"
    force_delete_nonempty: true
    state: absent
  ignore_errors: true


